table People
	lineageTag: 31679fc2-0394-43c6-a3d6-0ff1ec34e1e1

	column Person
		dataType: string
		lineageTag: 2c6bd034-f976-42c7-990c-75fbe6422000
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f04c10bd-945f-4836-9596-f7251f1be2f7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition People = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HemantMistryMAQSoftw\Downloads\global_superstore_2016.xlsx"), null, true),
				    People_Sheet = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(People_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Person", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

