table reports
	lineageTag: 92acaca9-b531-4ed7-bea9-34ae11ea4b6e

	column '@odata.context'
		dataType: string
		lineageTag: ae4a26c2-f327-4c9d-b438-0c790d49f85f
		summarizeBy: none
		sourceColumn: @odata.context

		annotation SummarizationSetBy = Automatic

	column 'value.id'
		dataType: string
		lineageTag: 7d32bb85-6e1f-4ad8-9bdf-8b19d6b634ae
		summarizeBy: none
		sourceColumn: value.id

		annotation SummarizationSetBy = Automatic

	column 'value.reportType'
		dataType: string
		lineageTag: 6e6b89ad-c1d9-470e-911c-365d2bd360a1
		summarizeBy: none
		sourceColumn: value.reportType

		annotation SummarizationSetBy = Automatic

	column 'value.name'
		dataType: string
		lineageTag: d127ebff-ccea-4f38-abb7-797ab7672251
		summarizeBy: none
		sourceColumn: value.name

		annotation SummarizationSetBy = Automatic

	column 'value.webUrl'
		dataType: string
		lineageTag: bca24d71-321b-487a-a1bd-32285ab592ba
		summarizeBy: none
		sourceColumn: value.webUrl

		annotation SummarizationSetBy = Automatic

	column 'value.embedUrl'
		dataType: string
		lineageTag: 5e151650-db2f-415d-afab-01dc535792bd
		summarizeBy: none
		sourceColumn: value.embedUrl

		annotation SummarizationSetBy = Automatic

	column 'value.isFromPbix'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2d65ea4c-1947-4862-a34a-7cd4841f5519
		summarizeBy: none
		sourceColumn: value.isFromPbix

		annotation SummarizationSetBy = Automatic

	column 'value.isOwnedByMe'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 913746c6-4f8c-415b-9076-944c5216ca0f
		summarizeBy: none
		sourceColumn: value.isOwnedByMe

		annotation SummarizationSetBy = Automatic

	column 'value.datasetId'
		dataType: string
		lineageTag: e03faaf0-dce4-40b2-ad9d-32bd6a772751
		summarizeBy: none
		sourceColumn: value.datasetId

		annotation SummarizationSetBy = Automatic

	column 'value.datasetWorkspaceId'
		dataType: string
		lineageTag: 836d2aee-310f-4aae-b413-8855b3f9c1fe
		summarizeBy: none
		sourceColumn: value.datasetWorkspaceId

		annotation SummarizationSetBy = Automatic

	column 'value.users'
		dataType: string
		lineageTag: 8399faaa-37f7-4270-8e96-bcb6d1d13810
		summarizeBy: none
		sourceColumn: value.users

		annotation SummarizationSetBy = Automatic

	column 'value.subscriptions'
		dataType: string
		lineageTag: f9be7f3d-fc4b-493a-86a6-34ddbc4bcc79
		summarizeBy: none
		sourceColumn: value.subscriptions

		annotation SummarizationSetBy = Automatic

	partition reports = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://api.powerbi.com/v1.0/myorg/groups/3bf5b678-13cd-4ffe-bdbb-28941f9d30d6/reports", [Headers=[Authorization="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyIsImtpZCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZTRkOThkZDItOTE5OS00MmU1LWJhOGItZGEzZTc2M2VkZTJlLyIsImlhdCI6MTcyMDY4NjgyMCwibmJmIjoxNzIwNjg2ODIwLCJleHAiOjE3MjA2OTE1NzMsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WEFBQUF0bit3cEtJQVpoSUZBOXBpMTFpYWFlSUFoS29hb3pobXRBZnZWSU9YQWYwYW1lUUJtd2xmNUdKcWVpVDVEa1VoWmJvdGxUOWxvTkRGZjBxWnEvSnZGNGo3bDFTSlRZMGJ2VWRsNTFJYk1SVT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMThmYmNhMTYtMjIyNC00NWY2LTg1YjAtZjdiZjJiMzliM2YzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJZYWR1d2Fuc2hpIiwiZ2l2ZW5fbmFtZSI6IlJpc2hhYmgiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNC45OC4yNDIuMjQzIiwibmFtZSI6IlJpc2hhYmggWWFkdXdhbnNoaSB8IE1BUSBTb2Z0d2FyZSIsIm9pZCI6ImYwODUxM2RjLTMzYzMtNDFjNS05ZWE2LTI5ZTUyN2MxMWFiZiIsInB1aWQiOiIxMDAzMjAwMkYzQUE0MDY4IiwicmgiOiIwLkFRY0EwbzNaNUptUjVVSzZpOW8tZGo3ZUxna0FBQUFBQUFBQXdBQUFBQUFBQUFBSEFEUS4iLCJzY3AiOiJBcHAuUmVhZC5BbGwgQ2FwYWNpdHkuUmVhZC5BbGwgQ2FwYWNpdHkuUmVhZFdyaXRlLkFsbCBDb250ZW50LkNyZWF0ZSBEYXNoYm9hcmQuUmVhZC5BbGwgRGFzaGJvYXJkLlJlYWRXcml0ZS5BbGwgRGF0YWZsb3cuUmVhZC5BbGwgRGF0YWZsb3cuUmVhZFdyaXRlLkFsbCBEYXRhc2V0LlJlYWQuQWxsIERhdGFzZXQuUmVhZFdyaXRlLkFsbCBHYXRld2F5LlJlYWQuQWxsIEdhdGV3YXkuUmVhZFdyaXRlLkFsbCBJdGVtLkV4ZWN1dGUuQWxsIEl0ZW0uUmVhZFdyaXRlLkFsbCBJdGVtLlJlc2hhcmUuQWxsIE9uZUxha2UuUmVhZC5BbGwgT25lTGFrZS5SZWFkV3JpdGUuQWxsIFBpcGVsaW5lLkRlcGxveSBQaXBlbGluZS5SZWFkLkFsbCBQaXBlbGluZS5SZWFkV3JpdGUuQWxsIFJlcG9ydC5SZWFkV3JpdGUuQWxsIFJlcHJ0LlJlYWQuQWxsIFN0b3JhZ2VBY2NvdW50LlJlYWQuQWxsIFN0b3JhZ2VBY2NvdW50LlJlYWRXcml0ZS5BbGwgVGVuYW50LlJlYWQuQWxsIFRlbmFudC5SZWFkV3JpdGUuQWxsIFVzZXJTdGF0ZS5SZWFkV3JpdGUuQWxsIFdvcmtzcGFjZS5HaXRDb21taXQuQWxsIFdvcmtzcGFjZS5HaXRVcGRhdGUuQWxsIFdvcmtzcGFjZS5SZWFkLkFsbCBXb3Jrc3BhY2UuUmVhZFdyaXRlLkFsbCIsInN1YiI6ImdwbHhZN3oyU2VlbmxqQUdSWnlrTmp6N254SnBMeTRJVXFoZFEtUEIwcUEiLCJ0aWQiOiJlNGQ5OGRkMi05MTk5LTQyZTUtYmE4Yi1kYTNlNzYzZWRlMmUiLCJ1bmlxdWVfbmFtZSI6InJpc2hhYmh5QG1hcXNvZnR3YXJlLmNvbSIsInVwbiI6InJpc2hhYmh5QG1hcXNvZnR3YXJlLmNvbSIsInV0aSI6ImlWbmkwNC1yNkVPQzJwSkFWTk1NQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDYifQ.xeaUlKSo-3ZiKVjFHSA-SpgpniOdzprty70tNy4kWkxmdOTHE4Idz-4-PW0Hu1cEnE6yQkovwPPeDbHDgPNKTuGZCjFwKI7OCNHbKL1yy5LQjNbMqN_qubxbAW3TS78QPNBcO-4gEUKml8_7zb_1ViIs_ycDr6mBsploxPrBD0218bTqjurbBWSdJYy5wwSPQp0ZlPM1h7kzKb6whHTcMkUbKUIbuTv0dbmkJNMoesvE3slc5Jrpegz91xmn5GxizvocCnPhwygPhF2fkflSknYiPKBlhta0_vzO4ZSVvOK3v79gXXAPFFAci-_EWEsUMHVD-6FgM06jZpE2xPjOrQ"]])),
				    #"Converted to Table" = Table.FromRecords({Source}),
				    #"Expanded value" = Table.ExpandListColumn(#"Converted to Table", "value"),
				    #"Expanded value1" = Table.ExpandRecordColumn(#"Expanded value", "value", {"id", "reportType", "name", "webUrl", "embedUrl", "isFromPbix", "isOwnedByMe", "datasetId", "datasetWorkspaceId", "users", "subscriptions"}, {"value.id", "value.reportType", "value.name", "value.webUrl", "value.embedUrl", "value.isFromPbix", "value.isOwnedByMe", "value.datasetId", "value.datasetWorkspaceId", "value.users", "value.subscriptions"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded value1",{{"@odata.context", type text}, {"value.id", type text}, {"value.reportType", type text}, {"value.name", type text}, {"value.webUrl", type text}, {"value.embedUrl", type text}, {"value.isFromPbix", type logical}, {"value.isOwnedByMe", type logical}, {"value.datasetId", type text}, {"value.datasetWorkspaceId", type text}, {"value.users", type any}, {"value.subscriptions", type any}}),
				    #"Expanded value.subscriptions" = Table.ExpandListColumn(#"Changed Type", "value.subscriptions"),
				    #"Expanded value.users" = Table.ExpandListColumn(#"Expanded value.subscriptions", "value.users")
				in
				    #"Expanded value.users"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

