table 'scheduled refreshes'
	lineageTag: 153dd049-c84e-4121-ba8f-5e3140949fa8

	column '@odata.context'
		dataType: string
		lineageTag: fd5ead44-af02-421f-b46c-fe2b4653821b
		summarizeBy: none
		sourceColumn: @odata.context

		annotation SummarizationSetBy = Automatic

	column days
		dataType: string
		lineageTag: 821fb323-8a32-4fd5-ac08-cb9409489c5b
		summarizeBy: none
		sourceColumn: days

		annotation SummarizationSetBy = Automatic

	column times
		dataType: string
		lineageTag: 0eb2a656-dd90-4621-aee7-a7a62366cfa2
		summarizeBy: none
		sourceColumn: times

		annotation SummarizationSetBy = Automatic

	column enabled
		dataType: string
		lineageTag: ceb813e3-5160-4ec1-89a5-b82866307403
		summarizeBy: none
		sourceColumn: enabled

		annotation SummarizationSetBy = Automatic

	column localTimeZoneId
		dataType: string
		lineageTag: 5b56e078-1324-42a1-8bae-50a7b08b69bb
		summarizeBy: none
		sourceColumn: localTimeZoneId

		annotation SummarizationSetBy = Automatic

	column notifyOption
		dataType: string
		lineageTag: 700b58c3-3f26-4676-9f55-280e662942a5
		summarizeBy: none
		sourceColumn: notifyOption

		annotation SummarizationSetBy = Automatic

	partition 'scheduled refreshes' = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://api.powerbi.com/v1.0/myorg/groups/3bf5b678-13cd-4ffe-bdbb-28941f9d30d6/datasets/235c87b6-b265-43ed-a9d8-aab0ed7e8866/refreshSchedule", [Headers=[Authorization="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyIsImtpZCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZTRkOThkZDItOTE5OS00MmU1LWJhOGItZGEzZTc2M2VkZTJlLyIsImlhdCI6MTcyMDY4NjgyMCwibmJmIjoxNzIwNjg2ODIwLCJleHAiOjE3MjA2OTE1NzMsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WEFBQUF0bit3cEtJQVpoSUZBOXBpMTFpYWFlSUFoS29hb3pobXRBZnZWSU9YQWYwYW1lUUJtd2xmNUdKcWVpVDVEa1VoWmJvdGxUOWxvTkRGZjBxWnEvSnZGNGo3bDFTSlRZMGJ2VWRsNTFJYk1SVT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMThmYmNhMTYtMjIyNC00NWY2LTg1YjAtZjdiZjJiMzliM2YzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJZYWR1d2Fuc2hpIiwiZ2l2ZW5fbmFtZSI6IlJpc2hhYmgiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNC45OC4yNDIuMjQzIiwibmFtZSI6IlJpc2hhYmggWWFkdXdhbnNoaSB8IE1BUSBTb2Z0d2FyZSIsIm9pZCI6ImYwODUxM2RjLTMzYzMtNDFjNS05ZWE2LTI5ZTUyN2MxMWFiZiIsInB1aWQiOiIxMDAzMjAwMkYzQUE0MDY4IiwicmgiOiIwLkFRY0EwbzNaNUptUjVVSzZpOW8tZGo3ZUxna0FBQUFBQUFBQXdBQUFBQUFBQUFBSEFEUS4iLCJzY3AiOiJBcHAuUmVhZC5BbGwgQ2FwYWNpdHkuUmVhZC5BbGwgQ2FwYWNpdHkuUmVhZFdyaXRlLkFsbCBDb250ZW50LkNyZWF0ZSBEYXNoYm9hcmQuUmVhZC5BbGwgRGFzaGJvYXJkLlJlYWRXcml0ZS5BbGwgRGF0YWZsb3cuUmVhZC5BbGwgRGF0YWZsb3cuUmVhZFdyaXRlLkFsbCBEYXRhc2V0LlJlYWQuQWxsIERhdGFzZXQuUmVhZFdyaXRlLkFsbCBHYXRld2F5LlJlYWQuQWxsIEdhdGV3YXkuUmVhZFdyaXRlLkFsbCBJdGVtLkV4ZWN1dGUuQWxsIEl0ZW0uUmVhZFdyaXRlLkFsbCBJdGVtLlJlc2hhcmUuQWxsIE9uZUxha2UuUmVhZC5BbGwgT25lTGFrZS5SZWFkV3JpdGUuQWxsIFBpcGVsaW5lLkRlcGxveSBQaXBlbGluZS5SZWFkLkFsbCBQaXBlbGluZS5SZWFkV3JpdGUuQWxsIFJlcG9ydC5SZWFkV3JpdGUuQWxsIFJlcHJ0LlJlYWQuQWxsIFN0b3JhZ2VBY2NvdW50LlJlYWQuQWxsIFN0b3JhZ2VBY2NvdW50LlJlYWRXcml0ZS5BbGwgVGVuYW50LlJlYWQuQWxsIFRlbmFudC5SZWFkV3JpdGUuQWxsIFVzZXJTdGF0ZS5SZWFkV3JpdGUuQWxsIFdvcmtzcGFjZS5HaXRDb21taXQuQWxsIFdvcmtzcGFjZS5HaXRVcGRhdGUuQWxsIFdvcmtzcGFjZS5SZWFkLkFsbCBXb3Jrc3BhY2UuUmVhZFdyaXRlLkFsbCIsInN1YiI6ImdwbHhZN3oyU2VlbmxqQUdSWnlrTmp6N254SnBMeTRJVXFoZFEtUEIwcUEiLCJ0aWQiOiJlNGQ5OGRkMi05MTk5LTQyZTUtYmE4Yi1kYTNlNzYzZWRlMmUiLCJ1bmlxdWVfbmFtZSI6InJpc2hhYmh5QG1hcXNvZnR3YXJlLmNvbSIsInVwbiI6InJpc2hhYmh5QG1hcXNvZnR3YXJlLmNvbSIsInV0aSI6ImlWbmkwNC1yNkVPQzJwSkFWTk1NQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDYifQ.xeaUlKSo-3ZiKVjFHSA-SpgpniOdzprty70tNy4kWkxmdOTHE4Idz-4-PW0Hu1cEnE6yQkovwPPeDbHDgPNKTuGZCjFwKI7OCNHbKL1yy5LQjNbMqN_qubxbAW3TS78QPNBcO-4gEUKml8_7zb_1ViIs_ycDr6mBsploxPrBD0218bTqjurbBWSdJYy5wwSPQp0ZlPM1h7kzKb6whHTcMkUbKUIbuTv0dbmkJNMoesvE3slc5Jrpegz91xmn5GxizvocCnPhwygPhF2fkflSknYiPKBlhta0_vzO4ZSVvOK3v79gXXAPFFAci-_EWEsUMHVD-6FgM06jZpE2xPjOrQ"]])),
				    #"Converted to Table" = Table.FromRecords({Source}),
				    #"Expanded days" = Table.ExpandListColumn(#"Converted to Table", "days"),
				    #"Expanded times" = Table.ExpandListColumn(#"Expanded days", "times")
				in
				    #"Expanded times"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

