table 'Meaure Table'
	lineageTag: 5887da30-d9ad-4dd7-ace5-2786ec34338f

	measure 'Reports with more than 8 Refreshes' = SUMX(PowerBIRefreshesScheduled,if(PowerBIRefreshesScheduled[refreshCountPerDay]>8,1,0))
		formatString: 0
		lineageTag: ed9c2497-59a7-45a6-b07d-6bb1fc775746

	measure 'Count of Orphan Datasets' = SUMX(PowerBIDatasets,CALCULATE(if(ISBLANK(count(PowerBIReports[datasetId])),1,0)))
		formatString: 0
		lineageTag: 760bbd56-c167-42bc-aa56-404bd5842d25

	measure 'Count of datasets taking more than one hours' = SUMX(PowerBIRefreshesHistory,if(PowerBIRefreshesHistory[refreshDurationMoreThan1Hr],1,0))
		formatString: 0
		lineageTag: ecb996a2-431b-4550-aa88-d2af48edd7bb

	partition 'Meaure Table' = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

