name: Update Power BI from Git

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  update-powerbi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Commit Hash
        id: get_commit
         run: |
          LATEST_COMMIT_HASH=$(git rev-parse HEAD)
          echo "Latest Commit Hash: $LATEST_COMMIT_HASH"
          echo "LATEST_COMMIT_HASH=$LATEST_COMMIT_HASH" >> $GITHUB_ENV

      - name: Authenticate with Azure and Get Access Token
        id: get_token
        run: |
          RESPONSE=$(curl -X POST "https://login.microsoftonline.com/${{ secrets.POWERBI_TENANT_ID }}/oauth2/v2.0/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials" \
          -d "client_id=${{ secrets.POWERBI_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.POWERBI_CLIENT_SECRET }}" \
          -d "scope=https://analysis.windows.net/powerbi/api/.default")

          TOKEN=$(echo $RESPONSE | jq -r '.access_token')

          echo "::add-mask::$TOKEN"  # Mask token for security
          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Trigger Power BI Update from Git
        run: |
          curl -X POST "https://api.powerbi.com/v1.0/myorg/groups/${{ secrets.POWERBI_WORKSPACE_ID }}/updateFromGit" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
                "workspaceHead": "${{ secrets.POWERBI_WORKSPACE_HEAD }}",
                "remoteCommitHash": "'"${LATEST_COMMIT_HASH}"'",
                "options": {
                  "allowOverrideItems": true
                }
              }'
