name: Update Power BI from Git

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  update-powerbi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Azure and Get Access Token
        id: get_token
        run: |
          python3 - <<EOF
          import requests
          import os

          tenant_id = os.environ['POWERBI_TENANT_ID']
          client_id = os.environ['POWERBI_CLIENT_ID']
          client_secret = os.environ['POWERBI_CLIENT_SECRET']
          scope = "https://api.fabric.microsoft.com/.default"
          url = f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"

          data = {
              "grant_type": "client_credentials",
              "client_id": client_id,
              "client_secret": client_secret,
              "scope": scope
          }

          headers = {"Content-Type": "application/x-www-form-urlencoded"}
          response = requests.post(url, data=data, headers=headers)
          response_json = response.json()
          token = response_json.get("access_token", "")

          print("Raw Response:", response_json)
          print("Access Token:", token)

          if not token:
              print("Error: Failed to retrieve a valid token")
              exit(1)

          with open("token.txt", "w") as f:
              f.write(token)

          print("Base64 Encoded Token:", token.encode("utf-8").hex())
          EOF

      - name: Fetch Workspace Git Status
        run: |
          ACCESS_TOKEN=$(cat token.txt)
          STATUS_RESPONSE=$(curl -s -X GET "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.POWERBI_WORKSPACE_ID }}/git/status" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json")

          echo "Git Status Response: $STATUS_RESPONSE"

          WORKSPACE_HEAD=$(echo $STATUS_RESPONSE | jq -r '.workspaceHead')
          REMOTE_COMMIT_HASH=$(echo $STATUS_RESPONSE | jq -r '.remoteCommitHash')

          echo "WORKSPACE_HEAD=$WORKSPACE_HEAD" >> $GITHUB_ENV
          echo "REMOTE_COMMIT_HASH=$REMOTE_COMMIT_HASH" >> $GITHUB_ENV

      - name: Trigger Power BI Update from Git
        run: |
          ACCESS_TOKEN=$(cat token.txt)
          UPDATE_RESPONSE=$(curl -s -X POST "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.POWERBI_WORKSPACE_ID }}/git/updateFromGit" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
                "workspaceHead": "'$WORKSPACE_HEAD'",
                "remoteCommitHash": "'$REMOTE_COMMIT_HASH'",
                "options": { "allowOverrideItems": true }
              }')
          
          echo "Update Response: $UPDATE_RESPONSE"
